/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tools.gui;

import game.Prezent.db.DB;
import javax.swing.JFrame;

/**
 *
 * @author BotNaEasyEnv
 */
public class MapCreator extends javax.swing.JFrame {

    
    private MapPanel map;
    private static DB db;
    /**
     * Creates new form MapCreator
     */
    public MapCreator() {
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        //setUndecorated(true);
        setTitle("Map Creator v.1.0");
        initComponents();
        loadDB();
        map = new MapPanel();
        mapPanel.add(map);
    }
    
    private void loadDB(){
        try{
            db = new DB("bot", "123456");
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public static DB getDB(){
        return db;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        saveMenu = new javax.swing.JMenu();
        loadMenu = new javax.swing.JMenu();
        newMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mapPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mapPanel, java.awt.BorderLayout.CENTER);

        saveMenu.setText("Save");
        jMenuBar1.add(saveMenu);

        loadMenu.setText("Load");
        jMenuBar1.add(loadMenu);

        newMenu.setText("New");
        jMenuBar1.add(newMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MapCreator creator = new MapCreator();
                creator.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu loadMenu;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JMenu newMenu;
    private javax.swing.JMenu saveMenu;
    // End of variables declaration//GEN-END:variables
}
